name: Update LanguageTool SPEC

on:
  schedule:
  - cron: "0 5 * * *"

jobs:
  update-languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare git
        run: |
          git config --global user.email 'rpm-bot@lkiesow.io'
          git config --global user.name 'RPM Bot'

      - name: upload SPEC file
        run: |
          ./update-LanguageTool.sh
